name = "duel-simulator"
pages_build_output_dir = "dist"
compatibility_date = "2024-12-01"

# Environment variables
[vars]
ENVIRONMENT = "development"

# D1 Database binding for Pages
[[d1_databases]]
binding = "DB"
database_name = "duel-simulator"
database_id = "1cb9b5cb-8700-4921-9312-add657a08fe5"

# R2 Storage binding for Pages
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "duel-simulator-images"