name = "duel-simulator"
pages_build_output_dir = "dist"
compatibility_date = "2024-12-01"

# Environment variables
[vars]
ENVIRONMENT = "production"

# D1 Database binding for Pages
[[d1_databases]]
binding = "DB"
database_name = "duel-simulator"
database_id = "f2589fd9-5372-4356-b73f-537d9ecef222"
migrations_dir = "db/migrations"

# R2 Storage binding for Pages
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "duel-simulator-images"
